Updated image id to use the version

diff --git a/build b/build
--- a/build
+++ b/build
@@ -11,9 +11,14 @@ ERROR="Error building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile), due t
 
 if [[ ! -z "$VERSION" ]] && [[ "$VERSION" != "latest" ]]; then
   debug "Tagging $NAME $VERSION"
+  DOCKER_ID=`VERSION=latest NAME=$NAME ./submodules/docker/image`
 
-  DOCKER_ID=$(NAME=$NAME ./submodules/docker/image)
-  debug "  -- Found $NAME image $DOCKER_ID"
+  if [[ -z "$DOCKER_ID" ]]; then
+    error "Unable to load docker image id for $NAME"
+    exit 1
+  fi
+
+  debug "  -- Found $NAME image $DOCKER_ID ($VERSION)"
   (cd ${LAUNCHER_DIR} &&  IGNORE=$(docker tag $DOCKER_ID $NAME:$VERSION > $DOCKER_OUTPUT 2>&1))
   ERROR="Error tagging DOCKER container $NAME ($VERSION), due to ..." ./submodules/bootstrap/failonerrors $? $DOCKER_OUTPUT
   [ $? -ne 0 ] && exit 1
