Improving robustness of bash with error propagation

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,4 +1,19 @@
 #!/bin/bash
+source ./submodules/bootstrap/logging
 
-echo "  -- Building $NAME (${LAUNCHER_DIR}/Dockerfile)"
-(cd ${LAUNCHER_DIR} && docker build -t $NAME .)
+notify "  -- Building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile)"
+if [[ "$LOGLEVEL" -le "$DEBUG_LEVEL" ]]; then
+  DOCKER_OUTPUT=${LAUNCHER_DIR}/docker_build.log
+  # (cd ${LAUNCHER_DIR} && docker build -t $NAME .)
+else
+  DOCKER_OUTPUT=/dev/null
+fi
+
+(cd ${LAUNCHER_DIR} && DOCKER_ERRORS=$(docker build -t $NAME . 2>&1 > $DOCKER_OUTPUT))
+debug_all $DOCKER_OUTPUT
+
+if [[ ! -z "$DOCKER_ERRORS" ]]; then
+  error "Error building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile), due to ..."
+  error $DOCKER_ERRORS
+  exit 1
+fi
