Moving ./submodules to ./bits

diff --git a/build b/build
--- a/build
+++ b/build
@@ -1,17 +1,17 @@
 #!/bin/bash
-[[ -z "$INFO_LEVEL" ]] && source ./submodules/bootstrap/logging
+[[ -z "$INFO_LEVEL" ]] && source ./bits/bootstrap/logging
 
 notify "  -- Building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile)"
 DOCKER_OUTPUT=${LAUNCHER_DIR}/docker_build.log
 debug "  -- Run 'tail -f ${DOCKER_OUTPUT}' to watch build logs live"
 
 (cd ${LAUNCHER_DIR} && IGNORE=$(docker build -t $NAME . > $DOCKER_OUTPUT 2>&1))
-ERROR="Error building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile), due to ..." ./submodules/bootstrap/failonerrors $? $DOCKER_OUTPUT
+ERROR="Error building DOCKER container $NAME (${LAUNCHER_DIR}/Dockerfile), due to ..." ./bits/bootstrap/failonerrors $? $DOCKER_OUTPUT
 [ $? -ne 0 ] && exit 1
 
 if [[ ! -z "$VERSION" ]] && [[ "$VERSION" != "latest" ]]; then
   debug "  -- Tagging $NAME $VERSION"
-  DOCKER_ID=`VERSION=latest NAME=$NAME ./submodules/docker/image`
+  DOCKER_ID=`VERSION=latest NAME=$NAME ./bits/docker/image`
 
   if [[ -z "$DOCKER_ID" ]]; then
     error "Unable to load docker image id for $NAME"
@@ -20,7 +20,7 @@ if [[ ! -z "$VERSION" ]] && [[ "$VERSION" != "latest" ]]; then
 
   debug "  -- Found $NAME image $DOCKER_ID ($VERSION)"
   (cd ${LAUNCHER_DIR} &&  IGNORE=$(docker tag $DOCKER_ID $NAME:$VERSION > $DOCKER_OUTPUT 2>&1))
-  ERROR="Error tagging DOCKER container $NAME ($VERSION), due to ..." ./submodules/bootstrap/failonerrors $? $DOCKER_OUTPUT
+  ERROR="Error tagging DOCKER container $NAME ($VERSION), due to ..." ./bits/bootstrap/failonerrors $? $DOCKER_OUTPUT
   [ $? -ne 0 ] && exit 1
   debug "  -- Successgully tagged $NAME $VERSION"
 fi
diff --git a/load b/load
--- a/load
+++ b/load
@@ -1,5 +1,5 @@
 #!/bin/bash
-source ./submodules/bootstrap/logging
+source ./bits/bootstrap/logging
 
 export DOCKER_ASSETS_DIR=${DOCKER_ASSETS_DIR-./assets/dockerimages}
 IMAGE_NAME=${IMAGE_NAME-$NAME:$VERSION}
@@ -11,11 +11,11 @@ if [[ "$FORCE_BUILD" == "skip" ]]; then
 
 elif [[ "$DOCKER_ASSETS_SERVER" != "local" ]]; then
   SERVER=$DOCKER_ASSETS_SERVER DIR=$DOCKER_ASSETS_DIR TO_DIR=/tmp \
-    FILENAME=${NAME}.${VERSION}.tar.gz ./submodules/bootstrap/scp
+    FILENAME=${NAME}.${VERSION}.tar.gz ./bits/bootstrap/scp
   [ $? -ne 0 ] && exit 1
   DOCKER_IMAGE_FILE=/tmp/${NAME}.${VERSION}.tar
 else
-  ./submodules/bootstrap/mkdir DOCKER_ASSETS_DIR
+  ./bits/bootstrap/mkdir DOCKER_ASSETS_DIR
   [ $? -ne 0 ] && exit 1
   DOCKER_IMAGE_FILE=$DOCKER_ASSETS_DIR/${NAME}.${VERSION}.tar
 fi
@@ -31,7 +31,7 @@ fi
 
 notify "  -- Loading $IMAGE_NAME from $DOCKER_IMAGE_FILE"
 SCRIPT_OUTPUT=$(docker load -i $DOCKER_IMAGE_FILE > $LOAD_OUTPUT 2>&1)
-ERROR="Unable to load $IMAGE_NAME from $DOCKER_IMAGE_FILE due to ..." ./submodules/bootstrap/failonerrors $? $LOAD_OUTPUT
+ERROR="Unable to load $IMAGE_NAME from $DOCKER_IMAGE_FILE due to ..." ./bits/bootstrap/failonerrors $? $LOAD_OUTPUT
 [ $? -ne 0 ] && exit 1
 
 if [[ -e $DOCKER_IMAGE_FILE.gz ]]; then
