Added load and load_or_build

diff --git a/save b/save
--- a/save
+++ b/save
@@ -1,4 +1,15 @@
 #!/bin/bash
+source ./submodules/bootstrap/logging
 
-IMAGE=$1
-docker save $IMAGE > ./assets/dockerimages/$IMAGE.tar
+export DOCKER_ASSETS_DIR=${DOCKER_ASSETS_DIR-./assets/dockerimages}
+IMAGE_NAME=${IMAGE_NAME-$NAME:$CLJ_VERSION}
+DOCKER_IMAGE_FILE=$DOCKER_ASSETS_DIR/${NAME}.${CLJ_VERSION}.tar
+SAVE_OUTPUT=${LAUNCHER_DIR}/docker_save.log
+
+./submodules/bootstrap/mkdir DOCKER_ASSETS_DIR
+[ $? -ne 0 ] && exit 1
+notify "  -- Saving $IMAGE_NAME to $DOCKER_IMAGE_FILE"
+SCRIPT_OUTPUT=$(docker save -o $DOCKER_IMAGE_FILE $IMAGE_NAME > $SAVE_OUTPUT 2>&1)
+ERROR="Unable to save $IMAGE_NAME to $DOCKER_IMAGE_FILE due to ..." ./submodules/bootstrap/failonerrors $? $SAVE_OUTPUT
+[ $? -ne 0 ] && exit 1
+debug "  -- DONE, Saving $IMAGE_NAME to $DOCKER_IMAGE_FILE"
